# Generated by Django 4.2.9 on 2024-02-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('number_players', models.IntegerField()),
                ('round_limit', models.IntegerField()),
                ('start_chips_minimum', models.IntegerField()),
                ('start_chips_maximum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('poker_chips', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='PlayerHasGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('player_game_chips', models.IntegerField()),
                ('player_in_game', models.BooleanField(default=True)),
                ('player_position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokerzin.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokerzin.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='join_game',
            field=models.ManyToManyField(through='app_pokerzin.PlayerHasGame', to='app_pokerzin.game'),
        ),
    ]
